#!/usr/bin/env bash

do_copy=false
while [[ $# -gt 0 ]] && [[ "$1" == "--"* ]]; do
    opt="$1"
    shift
    case "$opt" in
        "--copy")
            do_copy=true
            ;;
        *)
            echo 'install [options]'
            echo ''
            echo '  create symbolic links for files under this directory'
            echo '  and subdirectories in $HOME.'
            echo '  eg. $PWD/.zshrc will be symlinked to $HOME/.zshrc'
            echo ''
            echo 'where options:'
            echo '  --copy      copies the config files'
            echo ''
            exit 1
    esac
done

files=(
    bin/get-public-ip
    bin/gmum-connect
    bin/gmum-open-ports
    bin/wttr
    .config/nvim
    .config/zsh/functions/init-conda
    .gdbinit
    .gitconfig
    .tmux
    .tmux.conf
    .tmuxp
    .zshrc
)

[ ! -d "$HOME/bin" ] && mkdir "$HOME/bin"
[ ! -d "$HOME/.config/zsh/functions" ] && mkdir -p "$HOME/.config/zsh/functions"

if $do_copy; then
    for f in ${files[@]}; do
        (set -x;
            cp -Rf $PWD/$f $HOME/$f
        )
    done
else
    for f in ${files[@]}; do
        (set -x;
            ln -sf $PWD/$f $HOME/$f
        )
    done
fi

